server:
  port: 8081

spring:
  application:
    name: board-webflux
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/board
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db-init/schema.sql
logging:
  level:
    com.board: debug
    org.springframework.r2dbc.core: debug
